"""add thumbnail to category

Revision ID: 50fb241f15ee
Revises: 64d8a75d9edd
Create Date: 2026-02-07 11:08:22.323142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fb241f15ee'
down_revision: Union[str, None] = '64d8a75d9edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('thumbnail_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'categories', 'files', ['thumbnail_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'thumbnail_id')
    # ### end Alembic commands ###
