"""add product media and thumbnail

Revision ID: 64d8a75d9edd
Revises: f2313e835ee3
Create Date: 2026-02-06 22:30:46.143646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d8a75d9edd'
down_revision: Union[str, None] = 'f2313e835ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('thumbnail_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'products', 'files', ['thumbnail_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'thumbnail_id')
    op.drop_table('product_media')
    # ### end Alembic commands ###
