"""add image to product variant

Revision ID: e17a8f2ff712
Revises: 50fb241f15ee
Create Date: 2026-02-09 08:01:50.613531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17a8f2ff712'
down_revision: Union[str, None] = '50fb241f15ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('image_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'product_variants', 'files', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_column('product_variants', 'image_id')
    # ### end Alembic commands ###
